language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6-dev"

install:
  - "pip install -r requirements/csvalidate.txt -r requirements/tests.txt"

script:
  - "py.test"
  - "flake8 --ignore=F401"

sudo: false
cache: pip
